### ISSUE TITLE
starting work

### ISSUE THREAD

**Issue by emilioalaca** [tyburns/WHAPDataAnalysis#1]
At this point, we should be each creating new files for the scripts we will work on. Therefore, there will be no conflicts. The only problem might be that more than one of us starts working on the same type of script, which would not be a git conflict.

I will not be working on output tables or graphs. I am working on the calculation of the “universal” output files;
(1) all estimates, se’s and CI’s for subunits (qdt_mass_g_m2_yyyy.txt), 
(2) all comparisons among units within refuges (CompareSSMassWithinRefuge_yyy.txt, where XX is species,
(3) arbitrary comparisons of groups of subunits (e.g., management) and over years (tbd; EAL working on this).

I just pushed all the output files that are ready.

Let me know if this does not make sense.

**Comment by emilioalaca** [comment]
We can use issues to keep track of things within git hub. OK to repeat in email, but here it can be centralized

**Comment by kara-moore-oleary** [comment]
Makes sense. Thumbs up.
