### ISSUE TITLE
Extremely low yields in PIX 2021

### ISSUE THREAD

**Issue by emilioalaca** [tyburns/WHAPDataAnalysis#11]
Please, check the Compare years results.
In KRN, several yields were low, but some were greater than in 2020.
In PIX, **all* yields are much lower. We need to confirm that there are no errors in calculations or field measurements.

**Comment by rebeca-becdach** [comment]
Visually the subunits at PIX looked pretty low this year. I need to check through the calculations. One issue (maybe unrelated) that I noticed is that we did not survey subunit 5, but it still has values in the calculations. It's an upland unit

**Comment by emilioalaca** [comment]
OK. We identified VP globalid == {43322E8E-D9FB-422C-9DA2-5F3D993DFEAA} as being incorrectly classified as unit 5 but it should be PIX-4. I will correct in data correction step of main script and follow up with Eric.

Based on conversations with RB and TB, the low values in PIX are consistent with field observations. This issue is closed.
