### ISSUE TITLE
Kern Comparison Across years has Shrew Slough as a subunit

### ISSUE THREAD

**Issue by rebeca-becdach** [tyburns/WHAPDataAnalysis#13]
We did not survey the Shrew Slough. Not sure why that is showing up on the figures.

**Comment by tyburns** [comment]
Is this for the 2021 or other year analysis?

**Comment by emilioalaca** [comment]
This is for the 2021 data. It may be an error similar to the one about PIX 5 actually being PIX 4. I will assign to Eric.

**Comment by eross-usfws** [comment]
Thanks for the heads up. The Shrew Slough should be 4A-5. Those VP's were ones that had areas going into other MU's, so they got trimmed but the spatial join was still picking up a few that had edges on the border.

Revisited the workflow and updated the spatial join method to prevent this from coming up again in the future.

**Comment by emilioalaca** [comment]
Thanks! I will update the temp code for 2021 to correct this.
