### ISSUE TITLE
Dropping plant height?  

### ISSUE THREAD

**Issue by justin-mills-fws** [tyburns/WHAPDataAnalysis#18]
https://github.com/tyburns/WHAPDataAnalysis/blob/88178574bf588a5ea9fe24f72c119a2909da8364/WHAP2_SimBasedEstimates/WHAP2_DataChecks.Rmd#L546

https://github.com/tyburns/WHAPDataAnalysis/blob/c8aac57b3262dd46d82ac9e447bca1dd4c3ed890/WHAP2_SimBasedEstimates/WHAP2_DataChecks.Rmd#L229

Are we dropping the plant height data collection?  It is not in the SOP, so there are no instructions on how to do it.  If so, I'm pulling it out of the digital data sheet and it will no longer be in the incoming data.

**Comment by kara-moore-oleary** [comment]
You are correct, we are no longer collecting height data.

**Comment by emilioalaca** [comment]
We no longer use plant height.
