### ISSUE TITLE
New data files from Eric

### ISSUE THREAD

**Issue by emilioalaca** [tyburns/WHAPDataAnalysis#7]
Please, check the comments in the newDataStructures.

**Comment by emilioalaca** [comment]
I uploaded the complete data for 2021 and ran DataChecks2021.R.  There are a few minor issues that still have to be fixed in the data and processing from field to datafiles for analysis.

Please, pull the project and run DataChecks2021.R to see the details. The main issues to be resolved are:

mus uses Lit instead of LIT for column name.
For global ID's I recommend the following column names: vpsGlobalID, cpsGlobalID, qdtGlobalID.
For vernacularNames I recommend no spaces, as in OtherCover,  Watergrass, SwampTimothy and Smartweed. VPS and CPS files still have the names with spaces.
There are duplicates records in CPS (We need to investigate this as a group?)
Except for CPS, all other files have errors in the unitName and subunitName for KRN 4A-3, KRN 4A-5 and KRN 4A-6
CPS has some 0's as subunit names. Should be blank.
Quadrat size domain has been changed relative to last years to include "cm" at the end. I suggest that units be placed in the variable (column) name, not in the values.
There are data for PIX-5 and KRN-Shrew Slough which were not surveyed. Can the spatial join be corrected to avoid this?

Thanks!

**Comment by eross-usfws** [comment]
Looks like the script was still pulling from the old midseason data files. When I run that script on the data sent yesterday, several of those issues should be resolved:
-The MU's file should have LIT.
-No subunits should have a value of 0. 
-There should be no data attached to PIX-5 or KRN-Shrew Slough. 

For the other issues:
-global ID column changes look good. I'll incorporate that into the processing so it gets output as that. For seeds, should I just use seedGlobalID?
-I'm hesitant on the no-spaces for vernacularName. I'd like to keep things as easy as possible for anyone needing to add species in the future and think it'd make slightly more sense for someone to add the common name as is. 
-Duplicate records are still there for CP's - lets talk about 'em as a group
-Quadrat size change looks good. I will incorporate the units into the column name rather than the domain. 

Let me know if other issues come up!

**Comment by emilioalaca** [comment]
Apologies, Eric. I still had the old zip and confused it with the new one.

_-global ID column changes look good. I'll incorporate that into the processing so it gets output as that. For seeds, should I just use seedGlobalID?_

Yes, thanks.

_-I'm hesitant on the no-spaces for vernacularName. I'd like to keep things as easy as possible for anyone needing to add species in the future and think it'd make slightly more sense for someone to add the common name as is._

Sounds good.  I suggest that we have a master list of vernacular names as drop-down choices already linked to the species ID code. It would not be a good idea to let people add vernacular names ad libitum, lest the same species receives multiple names, each with a variety of spellings and capitalization. 

I think encountered a couple of other things:

### Wrong unit and subunit names for KRN in vps and qdt

`vps0 %>% group_by(LIT, unitName, subunitName) %>% count() %>% print(n = Inf)`

   LIT   unitName         subunitName     n
..
 5 KRN   4A-3             ""             10
 6 KRN   4A-5             ""             11
 7 KRN   4A-6             ""              9
...

I think the correct values should be

 5 KRN   4A             "4A-3"             10
 6 KRN   4A             "4A-5"             11
 7 KRN   4A             "4A-6"              9

### Blank space as subunit names in MDC

26 MDC   Flournoy Pond          " "                 1
27 MDC   Gadwall                     " "                 1
28 MDC   Grandma Tract 10.   " "                 1
29 MDC   Grandma Tract 11     " "                 1
30 MDC   Grandma Tract 2      " "                 1
31 MDC   Grandma Tract 3      " "                 1
32 MDC   Grandma Tract 4     " "                 1
33 MDC   Grandma Tract 8     " "                 1
34 MDC   Grandma Tract 9     " "                 1
35 MDC   House Field              " "                 1
36 MDC   J Pond                      " "                 1
37 MDC   Lower Goose Pond  " "                 1
38 MDC   Matney 3                  " "                 1
39 MDC   Matney 4 North       " "                 1
40 MDC   Matney 4 South       " "                 1
41 MDC   Matney 6                  " "                 1
42 MDC   Matney 7                  " "                 1
43 MDC   Matney 8                  " "                 1
44 MDC   South Dam Pond     " "                 1
45 MDC   Upper Goose Pond  " "                 1
46 PIX   1                                   ""                  0
47 PIX   2                                   ""                  0
48 PIX   2A                                ""                  0

It would be nice for those to be empty strings as in the other LITs.

Forgive me if I botched something again.

**Comment by emilioalaca** [comment]
I am having trouble making sense of the GlobalID_seed. See DataChecks2021.R at the end. It looks like the ID's are not identifying seed heads. There should be not duplicate GlobalID_seed for Swamp Timothy and there should be exactly 2 reps for each Watergrass, one in each measurement type.

**Comment by emilioalaca** [comment]
Resolved. unique ID's were added to files.
